### ISSUE TITLE
uWebTorrentTracker start up CentOS 7

### ISSUE THREAD

**Issue by wlvoipin** [DiegoRBaquero/uWebTorrentTracker#32]
Hi
 I am Rezan Khan and i installed UWT on Centos 7 and its working file but there is a issue i am getting, the issue is its must be start in terminal every time, so is there any solution to set start up automatically and run in background ? is there any solution please let me know.

Thank you
rezan Khan

**Comment by DiegoRBaquero** [comment]
forever or pm2

**Comment by DiegoRBaquero** [comment]
their docs are pretty good, see http://pm2.keymetrics.io/docs/usage/process-management/

**Comment by wlvoipin** [comment]
Thank you

i will try it.

Thanks a lot!
